// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gin} from '../models';
import {model} from '../models';

export function BlankList():Promise<gin.H>;

export function CreateBlank(arg1:model.CreateBlankTemp):Promise<gin.H>;

export function CreateDir(arg1:string,arg2:string):Promise<gin.H>;

export function GetBlank(arg1:string):Promise<gin.H>;

export function GetFolderChildren(arg1:string):Promise<gin.H>;

export function Greet(arg1:string):Promise<string>;

export function Upload(arg1:string,arg2:string):Promise<gin.H>;
