// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BlankList() {
  return window['go']['main']['App']['BlankList']();
}

export function CreateBlank(arg1) {
  return window['go']['main']['App']['CreateBlank'](arg1);
}

export function CreateDir(arg1, arg2) {
  return window['go']['main']['App']['CreateDir'](arg1, arg2);
}

export function GetBlank(arg1) {
  return window['go']['main']['App']['GetBlank'](arg1);
}

export function GetFolderChildren(arg1) {
  return window['go']['main']['App']['GetFolderChildren'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Upload(arg1, arg2) {
  return window['go']['main']['App']['Upload'](arg1, arg2);
}
